### ISSUE TITLE
Authorization does not work. (Taken from example)

### ISSUE THREAD

**Issue by ObjectNickname** [SteamRE/SteamKit#1010]
Connecting to Steam...
DBGListener - ServerList: Resolving server list
DBGListener - ServerList: Server list provider had no entries, will query SteamDirectory
DBGListener - ServerList: Resolved 200 servers
DBGListener - ServerList: Next server candidate: 162.254.197.39:27025 (Tcp)
DBGListener - 23c297cc7249451da72bd370bc9158b3/TcpConnection: Connecting to 162.254.197.39:27025...
DBGListener - 23c297cc7249451da72bd370bc9158b3/TcpConnection: Connected to 162.254.197.39:27025
DBGListener - 23c297cc7249451da72bd370bc9158b3/EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
DBGListener - 23c297cc7249451da72bd370bc9158b3/EnvelopeEncryptedConnection: Encryption result: OK
Connected to Steam! Logging in 'UserName'...
This account is SteamGuard protected!
Please enter the auth code sent to the email at gmail.com: DBGListener - 23c297cc7249451da72bd370bc9158b3/TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket()
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket()
   at SteamKit2.TcpConnection.NetLoop()

**Comment by ObjectNickname** [comment]
What could be the problem or is it just another bug?

**Comment by ObjectNickname** [comment]
Simple auth code
`
        public static void OnConnected(SteamClient.ConnectedCallback callback)
        {
            try
            {
                Console.WriteLine("Connected to Steam! Logging in '{0}'...", user);

                
                byte[] sentryHash = null;
                if (File.Exists("sentry.bin"))
                {
                    // if we have a saved sentry file, read and sha-1 hash it
                    byte[] sentryFile = File.ReadAllBytes("sentry.bin");
                    sentryHash = CryptoHelper.SHAHash(sentryFile);
                }
                
                steamUser.LogOn(new SteamUser.LogOnDetails
                {
                    Username = user,
                    Password = pass,

                    // in this sample, we pass in an additional authcode
                    // this value will be null (which is the default) for our first logon attempt
                  
                    AuthCode = authCode,

                    // if the account is using 2-factor auth, we'll provide the two factor code instead
                    // this will also be null on our first logon attempt
                    TwoFactorCode = twoFactorAuth,

                    // our subsequent logons use the hash of the sentry file as proof of ownership of the file
                    // this will also be null for our first (no authcode) and second (authcode only) logon attempts
                    SentryFileHash = sentryHash,
                });
      
            }
            catch (Exception ex)
            {
                Console.WriteLine($"{ex}");
                Console.WriteLine($"{ex.Message}");
            }
        }
`

**Comment by ObjectNickname** [comment]
My work until recently authorization code
 
        public static void Main(string[] args)

        {
            DebugLog.AddListener(new DBGListener());
            // Enable DebugLog in release builds
            DebugLog.Enabled = true;

            user = Confiugration.login;
            pass = Confiugration.password;
            steamClient = new SteamClient();
            // create the callback manager which will route callbacks to function calls
            manager = new CallbackManager(steamClient);
            gcMap = new CallbackStore();
            // get the steamuser handler, which is used for logging on after successfully connecting
            steamUser = steamClient.GetHandler<SteamUser>();
            steamFriends = steamClient.GetHandler<SteamFriends>();
            gameCoordinator = steamClient.GetHandler<SteamGameCoordinator>();
            // register a few callbacks we're interested in
            // these are registered upon creation to a callback manager, which will then route the callbacks
            // to the functions specifie

            manager.Subscribe<SteamClient.ConnectedCallback>(OnConnected);
            manager.Subscribe<SteamClient.DisconnectedCallback>(OnDisconnected);
            // this callback is triggered when the steam servers wish for the client to store the sentry file
            manager.Subscribe<SteamUser.UpdateMachineAuthCallback>(OnMachineAuth);
            // connections
            manager.Subscribe<SteamUser.LoggedOnCallback>(OnLoggedOn);
            manager.Subscribe<SteamUser.LoggedOffCallback>(OnLoggedOff);
            manager.Subscribe<SteamFriends.FriendsListCallback>(OnFriendsList);
            manager.Subscribe<SteamFriends.FriendAddedCallback>(OnFriendAdded);
            manager.Subscribe<SteamFriends.PersonaStateCallback>(OnPersonaState);
            // csgo
            manager.Subscribe<SteamGameCoordinator.MessageCallback>(OnGcMessage);

          //  AsyncJob<SteamFriends.FriendAddedCallback> asyncJob = new AsyncJob<SteamFriends.FriendAddedCallback>(steamClient, 123);
          //  Task<SteamFriends.FriendAddedCallback> asyncTask = asyncJob.ToTask();

            // timer
            HelloTimer = new System.Timers.Timer(1000);
            HelloTimer.AutoReset = true;
            HelloTimer.Elapsed += Knock;

            debug = true;
            isRunning = true;

            Console.WriteLine("Connecting to Steam...");

            // initiate the connection
            steamClient.Connect();

            // create our callback handling loop
            while (isRunning)
            {
                // in order for the callbacks to get routed, they need to be handled by the manager
                manager.RunWaitCallbacks(TimeSpan.FromSeconds(1));
            }
        }
        public static void OnConnected(SteamClient.ConnectedCallback callback)
        {
            try
            {
                Console.WriteLine("Connected to Steam! Logging in '{0}'...", user);

                
                byte[] sentryHash = null;
                if (File.Exists("sentry.bin"))
                {
                    // if we have a saved sentry file, read and sha-1 hash it
                    byte[] sentryFile = File.ReadAllBytes("sentry.bin");
                    sentryHash = CryptoHelper.SHAHash(sentryFile);
                }
                
                steamUser.LogOn(new SteamUser.LogOnDetails
                {
                    Username = user,
                    Password = pass,

                    // in this sample, we pass in an additional authcode
                    // this value will be null (which is the default) for our first logon attempt
                  
                    AuthCode = authCode,

                    // if the account is using 2-factor auth, we'll provide the two factor code instead
                    // this will also be null on our first logon attempt
                    TwoFactorCode = twoFactorAuth,

                    // our subsequent logons use the hash of the sentry file as proof of ownership of the file
                    // this will also be null for our first (no authcode) and second (authcode only) logon attempts
                    SentryFileHash = sentryHash,
                });
      
            }
            catch (Exception ex)
            {
                Console.WriteLine($"{ex}");
                Console.WriteLine($"{ex.Message}");
            }
        }
`

**Comment by yaakov-h** [comment]
Does Sample5_SteamGuard work, or is it also failing for you?

**Comment by yaakov-h** [comment]
Closing due to inactivity.
