### ISSUE TITLE
Disconnected from Steam

### ISSUE THREAD

**Issue by leikaiwei** [SteamRE/SteamKit#1121]
When I use SteamKit2 to connect to steam, it keeps failing

100 connections (approximately)
95 times it is OnDisconnected
5 times is OnConnected

Looking at the log is the error below, please help me :sob: 

I'm from China, the internet is in Hong Kong, China, my English is not good, sorry

`this.callbackManager.Subscribe<SteamClient.ConnectedCallback>(OnConnected);`
`this.callbackManager.Subscribe<SteamClient.DisconnectedCallback>(OnDisconnected);`
`steamClient.Connect();`

logs:
```
2022/8/23 18:30:00 <SteamFloatClient> <leikaiwei> Connecting to Steam...
2022/8/23 18:30:00 <MyListener> MyListener - ServerList: Resolving server list
2022/8/23 18:30:00 <MyListener> MyListener - ServerList: Server list provider had no entries, will query SteamDirectory
2022/8/23 18:30:01 <MyListener> MyListener - ServerList: Resolved 200 servers
2022/8/23 18:30:01 <MyListener> MyListener - ServerList: Next server candidate: 153.254.86.179:27017 (Tcp)
2022/8/23 18:30:01 <MyListener> MyListener - 7327c79f2b5b4aaea0fe905989a3f342/TcpConnection: Connecting to 153.254.86.179:27017...
2022/8/23 18:30:01 <MyListener> MyListener - 7327c79f2b5b4aaea0fe905989a3f342/TcpConnection: Connected to 153.254.86.179:27017
2022/8/23 18:30:01 <MyListener> MyListener - 7327c79f2b5b4aaea0fe905989a3f342/TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket()
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket()
   at SteamKit2.TcpConnection.NetLoop()
2022/8/23 18:30:01 <SteamFloatClient> <leikaiwei> Disconnected from Steam
2022/8/23 18:30:01 <SteamFloatClient> <leikaiwei> ErrorWhileConnecting
2022/8/23 18:30:30 <SteamFloatClient> <leikaiwei> Connecting to Steam...
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Resolving server list
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Resolving server list
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Server list provider had no entries, will query SteamDirectory
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Server list provider had no entries, will query SteamDirectory
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Resolved 200 servers
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Resolved 200 servers
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Next server candidate: 153.254.86.29:27017 (Tcp)
2022/8/23 18:30:30 <MyListener> MyListener - ServerList: Next server candidate: 153.254.86.29:27017 (Tcp)
2022/8/23 18:30:30 <MyListener> MyListener - d919e6876bc4474db4f39f6db4ca52dc/TcpConnection: Connecting to 153.254.86.29:27017...
2022/8/23 18:30:30 <MyListener> MyListener - d919e6876bc4474db4f39f6db4ca52dc/TcpConnection: Connecting to 153.254.86.29:27017...
2022/8/23 18:30:30 <MyListener> MyListener - d919e6876bc4474db4f39f6db4ca52dc/TcpConnection: Connected to 153.254.86.29:27017
2022/8/23 18:30:30 <MyListener> MyListener - d919e6876bc4474db4f39f6db4ca52dc/TcpConnection: Connected to 153.254.86.29:27017
2022/8/23 18:30:30 <MyListener> MyListener - d919e6876bc4474db4f39f6db4ca52dc/TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket()
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket()
   at SteamKit2.TcpConnection.NetLoop()
2022/8/23 18:30:30 <MyListener> MyListener - d919e6876bc4474db4f39f6db4ca52dc/TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket()
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket()
   at SteamKit2.TcpConnection.NetLoop()
2022/8/23 18:30:30 <SteamFloatClient> <leikaiwei> Disconnected from Steam
2022/8/23 18:30:30 <SteamFloatClient> <leikaiwei> ErrorWhileConnecting
```

I can use the steam client normally, the steam webpage (login account)
I think my network is fine

![image](https://user-images.githubusercontent.com/13110826/186138143-7edecd97-6314-4a50-b5b4-7c6145b688ab.png)

![image](https://user-images.githubusercontent.com/13110826/186138210-e466f3d0-5781-4b70-bb17-10b491c5ac06.png)

![image](https://user-images.githubusercontent.com/13110826/186139105-ba02eccf-e1b4-4257-b31f-6fb51687ce7e.png)

![image](https://user-images.githubusercontent.com/13110826/186139437-a4e7fb74-0224-4374-8260-97d8fca7e53f.png)

**Comment by xPaw** [comment]
Are you sure you're not trying to proxy it or something? It's possible that the China firewall is messing with it.

**Comment by leikaiwei** [comment]
@xPaw Thank you. I forgot to come here for feedback. After trying to use a proxy, everything is working fine now. Thank you.
