### ISSUE TITLE
[Bug]: RefreshSession

### ISSUE THREAD

**Issue by MixFix228** [SteamRE/SteamKit#1272]
2023-10-19 09:26:08|ArchiSteamFarm-291214|INFO|md|Connect() Connecting...
2023-10-19 09:26:08|ArchiSteamFarm-291214|INFO|md|OnDisconnected() Disconnected from Steam!
2023-10-19 09:26:08|ArchiSteamFarm-291214|INFO|md|OnConnected() Connected to Steam!
2023-10-19 09:26:08|ArchiSteamFarm-291214|INFO|md|OnConnected() Logging in...
2023-10-19 09:26:09|ArchiSteamFarm-291214|INFO|md|OnLoggedOn() Successfully logged on as 76561199437350123.
2023-10-19 09:26:14|ArchiSteamFarm-291214|INFO|md|StartFarming() We don't have anything to farm on this account!
2023-10-19 09:26:16|ArchiSteamFarm-291214|INFO|md|ResetGamesPlayed() Playing selected GamesPlayedWhileIdle: 252490, 1119730
2023-10-19 09:26:18|ArchiSteamFarm-291214|WARN|aes1|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 09:26:18|ArchiSteamFarm-291214|INFO|aes1|Connect() Connecting...
2023-10-19 09:26:18|ArchiSteamFarm-291214|INFO|aes1|OnDisconnected() Disconnected from Steam!
2023-10-19 09:26:18|ArchiSteamFarm-291214|INFO|aes1|OnConnected() Connected to Steam!
2023-10-19 09:26:18|ArchiSteamFarm-291214|INFO|aes1|OnConnected() Logging in...
2023-10-19 09:26:19|ArchiSteamFarm-291214|INFO|aes1|OnLoggedOn() Successfully logged on as 76561199096330224/maloletniedoxerisosutchlen.
2023-10-19 09:26:24|ArchiSteamFarm-291214|INFO|aes1|StartFarming() We don't have anything to farm on this account!
2023-10-19 09:26:26|ArchiSteamFarm-291214|INFO|aes1|ResetGamesPlayed() Playing selected GamesPlayedWhileIdle: 252490, 730, 1517290
2023-10-19 09:26:28|ArchiSteamFarm-291214|WARN|PeL|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 09:26:28|ArchiSteamFarm-291214|INFO|PeL|Connect() Connecting...
2023-10-19 09:26:28|ArchiSteamFarm-291214|INFO|PeL|OnDisconnected() Disconnected from Steam!
2023-10-19 09:26:28|ArchiSteamFarm-291214|INFO|PeL|OnConnected() Connected to Steam!
2023-10-19 09:26:28|ArchiSteamFarm-291214|INFO|PeL|OnConnected() Logging in...
2023-10-19 09:26:29|ArchiSteamFarm-291214|INFO|PeL|OnLoggedOn() Successfully logged on as 76561199544453046.
2023-10-19 09:26:34|ArchiSteamFarm-291214|INFO|PeL|StartFarming() We don't have anything to farm on this account!
2023-10-19 09:26:36|ArchiSteamFarm-291214|INFO|PeL|ResetGamesPlayed() Playing selected GamesPlayedWhileIdle: 252490, 730
### Which operating system are you running on?

Linux

### Which .NET Runtime are you running on?

.NET Framework

### Version

7.0.12

**Comment by xPaw** [comment]
This isn't a SreamKit issue.

**Comment by MixFix228** [comment]
> This isn't a SteamKit issue.

how to fix it?
