### ISSUE TITLE
Virtual Machine Failure due to GenerateMachineId

### ISSUE THREAD

**Issue by KenBeanNet** [SteamRE/SteamKit#200]
[code]
One or more errors occurred. ---> System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at SteamKit2.WindowsInfoProvider.GetDiskId()
   at SteamKit2.HardwareUtils.GenerateMachineID()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at SteamKit2.HardwareUtils.GetMachineID()
   at SteamKit2.SteamUser.LogOn(LogOnDetails details)
[/code]

When running in a virtual machine the DiskId is null I presume causing the method to fail and connection never to occur.

**Comment by VoiDeD** [comment]
Should be fixed in 624e657c5df3f72278dab28905c08dc6d12972aa. Going to need to figure out what we can do when Hyper-V isn't following the rules and isn't giving virtual disks serial numbers.

**Comment by KenBeanNet** [comment]
Figured id bump, 1.8 now causes the Login response to be PasswordIncorrect all the time.  My guess is still has to do with other open issues about MachineId.

**Comment by yaakov-h** [comment]
I'm closing this one as inactive. We've also since changed the machine ID implementation on Windows to not use WMI.
