### ISSUE TITLE
got EOF or empty keyname While Reading csgo_english.txt (KeyValues)

### ISSUE THREAD

**Issue by Alamer99** [SteamRE/SteamKit#258]
Heres My Code:
`static void Main(string[] args)
        {
            KeyValue csgo_english = new KeyValue();
            csgo_english.ReadFileAsText(@"C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\resource\csgo_english.txt");
        }`

It Ends Up With An Error

> System.Exception was unhandled
  HResult=-2146233088
  Message=RecursiveLoadFromBuffer: got EOF or empty keyname
  Source=SteamKit2
  StackTrace:
       at SteamKit2.KeyValue.RecursiveLoadFromBuffer(KVTextReader kvr)
       at SteamKit2.KeyValue.RecursiveLoadFromBuffer(KVTextReader kvr)
       at SteamKit2.KVTextReader..ctor(KeyValue kv, Stream input)
       at SteamKit2.KeyValue.ReadAsText(Stream input)
       at SteamKit2.KeyValue.ReadFileAsText(String filename)
       at Parse_CSGO_Language_File.Program.Main(String[] args) in c:\users\\------\documents\visual studio 2015\Projects\Parse CSGO Language File\Parse CSGO Language File\Program.cs:line 16
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by Netshroud** [comment]
This is a known issue with how we handle conditionals - see #232.

**Comment by Alamer99** [comment]
I Dont Want To Sound Like a Stupid But

Have You Ever Checked Valve's [KeyValues.h](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/tier1/KeyValues.h) And [KeyValues.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/tier1/KeyValues.cpp)

I Know Its C++ But Maybe You Could Find Something

**Comment by Netshroud** [comment]
Yes. This code is almost a 1:1 port of that.

Interestingly, it's conditional handling is virtually hardcoded, and looks to be somewhat out of date with the latest conditional options (e.g. $PS3).

**Comment by Alamer99** [comment]
in my opinion hardcoded conditional is better
you dont expect someone to be using SteamKit2 on Xbox/PS3 Right?

**Comment by Netshroud** [comment]
No, but somebody using SteamKit might want to extract Xbox/PS3 data, or even Linux data when running on Windows, etc.

**Comment by Alamer99** [comment]
good point however (not a c++ expert :P)
i noticed by reading valve's keyvalues they hardcoded it as _WIN32 so if we change it to _PS3 or _X360 that means it will extract the data we want right? if that works then maybe you can do it that way, make it hardcoded but the user can select which one he wants? (again i'm not a c++ expert that's just what came into my mind :) )

**Comment by xPaw** [comment]
For anyone looking, this is supported in https://github.com/SteamDatabase/ValveKeyValue

**Comment by yaakov-h** [comment]
And poorly in https://github.com/SteamRE/SteamKit/pull/684 😅
