### ISSUE TITLE
[Bug] SteamClient in UDP mode

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#260]
Noticed below crash from one of my ASF users:

```
29/03/2016 23:36:04 [!] EXCEPTION: UnhandledExceptionHandler() <Main> Unable to decrypt incoming packet
29/03/2016 23:36:06 [!] StackTrace:
   em SteamKit2.NetFilterEncryptionWithHMAC.ProcessIncoming(Byte[] data)
   em SteamKit2.UdpConnection.DispatchMessage()
   em SteamKit2.UdpConnection.ReceiveData(UdpPacket packet)
   em SteamKit2.UdpConnection.ReceivePacket(UdpPacket packet)
   em SteamKit2.UdpConnection.NetLoop()
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
29/03/2016 23:36:06 [!] EXCEPTION: UnhandledExceptionHandler() <Main> O comprimento dos dados a desencriptar é inválido (Translation: The length of the data to decrypt is invalid).
29/03/2016 23:36:06 [!] StackTrace:
   em System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   em System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   em System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   em System.IO.Stream.Close()
   em System.IO.Stream.Dispose()
   em SteamKit2.CryptoHelper.SymmetricDecrypt(Byte[] input, Byte[] key, Byte[]& iv)
   em SteamKit2.CryptoHelper.SymmetricDecryptHMACIV(Byte[] input, Byte[] key, Byte[] hmacSecret)
   em SteamKit2.NetFilterEncryptionWithHMAC.ProcessIncoming(Byte[] data)
```

(This is complete stacktrace, my logger logs exception and every inner exception recursively)

Crash is actually random, so it's probably because of network malfunctions, but can't say for sure.

As you can see from the stacktrace, this is the case only with SteamClient running in UDP protocol - https://github.com/SteamRE/SteamKit/issues/256

Let me know if you need DebugLog for this issue.

**Comment by Netshroud** [comment]
I tried to reproduce by changing `Sample7_ServerList` to use UDP (edit line 41) and it logs in as expected, no crash.

It may simply be that `UdpConnection` doesn't handle exceptions as gracefully as `TcpConnection`.

We catch `SocketException` in `UdpConnection.NetLoop` on line 407, but don't handle `IOException` or others.

@azuisleet?

**Comment by JustArchi** [comment]
Possible, as I noted, this exception is random, probably because of network malfunctions, so reproducing it can be quite difficult as well.

**Comment by JustArchi** [comment]
If you need to reproduce the bug, it should be enough to launch Steam, then launch a bot based on SK2 on the same machine in UDP mode (remember to set my newly introduced ```LoginID``` to something custom, so you won't get a session replace), then start any Valve game using UDP protocol such as CS:GO, Dota 2 or TF. Crash should come up soon.

**Comment by Royalgamer06** [comment]
Is this similar to [this issue](https://i.imgur.com/Jhupi1T.png) I am having? If not, I'll make a separate issue thread.

**Comment by JustArchi** [comment]
Got new one from SK2.0+

```
2017-12-17 01:07:17|ArchiSteamFarm-10483|FATAL|ASF|OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
at SteamKit2.EnvelopeEncryptedConnection.OnNetMsgReceived(Object sender, NetMsgEventArgs e)
at SteamKit2.UdpConnection.DispatchMessage()
at SteamKit2.UdpConnection.ReceiveData(UdpPacket packet)
at SteamKit2.UdpConnection.ReceivePacket(UdpPacket packet)
at SteamKit2.UdpConnection.NetLoop(Object param)
at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

I wonder how this was possible.

**Comment by yaakov-h** [comment]
Could be something that was inlined, as well.

Can you reproduce this on a platform that gives you line numbers from the PDBs?

**Comment by JustArchi** [comment]
I couldn't run into this bug myself under any circumstance, everything I forwarded here was users running into it, **[ref](http://steamcommunity.com/groups/ascfarm/discussions/1/1483232961032339275/#c2549465882925931554)**.

I've compiled latest SK2 in `Release` mode and I'll try to get more info from the PDBs from the user, but without guarantees if he wants to help 🙂. Just replacing `SteamKit2.dll` in published app and adding `.pdb` file next to it should do, right?

[Debug.zip](https://github.com/SteamRE/SteamKit/files/1565497/Debug.zip)

**Comment by yaakov-h** [comment]
I believe so.

**Comment by JustArchi** [comment]
I'm quite sure the issue here is with `e.Data` being `null`, this would also match original stacktrace we got from pre-SK2.0 times. I'll make sure to confirm this with appropriate log once we get one from the user.

**Comment by yaakov-h** [comment]
I don't think that can be null, and I did also do a by-hand audit of the codebase for nullability for SK 2.0. I may have missed something though, but I don't think it's `e.Data`.

https://github.com/SteamRE/SteamKit/blob/49e857b4e813aaf31ee470383f2f77157cd663b9/SteamKit2/SteamKit2/Networking/Steam3/UdpConnection.cs#L345

**Comment by yaakov-h** [comment]
Do you have `DebugLog` output?

`CMClient.GetPacketMsg` can return null, which would have us [promptly crash here](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Networking/Steam3/EnvelopeEncryptedConnection.cs#L80) in that case.

**Comment by JustArchi** [comment]
Sadly getting code line numbers turned out to be too hard (looks like self-contained apps have serious issues with portable PDB files, and even more problems with full ones, and we can't really install SDK there to run generic app).

But of course I got debug log, perhaps it'll help.

```
2017-12-18 21:29:11|ArchiSteamFarm-27083|DEBUG|ASF|WriteLine() UdpConnection | <- Recv'd Data Seq 14 Ack 9; 96 bytes; Message: 96 bytes 1 packets
2017-12-18 21:29:11|ArchiSteamFarm-27083|DEBUG|ASF|WriteLine() UdpConnection | Dispatching message; 96 bytes
2017-12-18 21:29:11|ArchiSteamFarm-27083|DEBUG|ASF|WriteLine() CMClient | Exception deserializing emsg 1740662045 (True).
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at SteamKit2.Internal.MsgHdrProtoBuf.Deserialize(Stream stream)
   at SteamKit2.PacketClientMsgProtobuf..ctor(EMsg eMsg, Byte[] data)
   at SteamKit2.Internal.CMClient.GetPacketMsg(Byte[] data)
2017-12-18 21:29:11|ArchiSteamFarm-27083|FATAL|ASF|OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamKit2.EnvelopeEncryptedConnection.OnNetMsgReceived(Object sender, NetMsgEventArgs e)
   at SteamKit2.UdpConnection.DispatchMessage()
   at SteamKit2.UdpConnection.ReceiveData(UdpPacket packet)
   at SteamKit2.UdpConnection.ReceivePacket(UdpPacket packet)
   at SteamKit2.UdpConnection.NetLoop(Object param)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by yaakov-h** [comment]
Looks like it's `CMClient.GetPacketMsg` then 😄
