### ISSUE TITLE
Weird unhandled exception

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#268]
I noticed in my log today:

```
20/04/2016 01:29:46 [*] INFO: OnConnected() Connected to Steam!
20/04/2016 01:29:47 [!] WARNING: OnLoggedOn() Unable to login to Steam: ServiceUnavailable
20/04/2016 01:29:47 [*] INFO: OnDisconnected() Disconnected from Steam!
20/04/2016 01:29:51 [!] EXCEPTION: UnhandledExceptionHandler() Object reference not set to an instance of an object
[!] StackTrace:   at SteamKit2.SteamFriends.SendChatRoomMessage (SteamKit2.SteamID steamIdChat, EChatEntryType type, System.String message) <0x40ce8aa0 + 0x0019e> in <filename unknown>:0
  at ArchiBoT.Bot.SendMessageToChannel (UInt64 steamID, System.String message) <0x7f40a0604c80 + 0x0017b> in <filename unknown>:0
  at ArchiBoT.Bot.SendMessageToOurChannel (System.String message) <0x7f40a0604f70 + 0x0006a> in <filename unknown>:0
  at ArchiBoT.TouhouGiveaways+<ParseGroupGiveaway>c__async5.MoveNext () <0x7f40a06d2a00 + 0x02921> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f40a0da2c00 + 0x00029> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f40a0da0a50 + 0x000a7> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f40a0da09d0 + 0x0006b> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f40a0da0980 + 0x0003a> in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () <0x7f40a0da1020 + 0x00012> in <filename unknown>:0
  at ArchiBoT.TouhouGiveaways+<ParseRecentGroupGiveaways>c__async6.MoveNext () <0x7f40a06d8000 + 0x00857> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f40a0da2c00 + 0x00029> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f40a0da0a50 + 0x000a7> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f40a0da09d0 + 0x0006b> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f40a0da0980 + 0x0003a> in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () <0x7f40a0da1020 + 0x00012> in <filename unknown>:0
  at ArchiBoT.TouhouGiveaways+<InitHouseKeeping>c__async12.MoveNext () <0x7f40a06d9f30 + 0x001e9> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f40a0da2c00 + 0x00029> in <filename unknown>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__1 (System.Object state) <0x7f40a0da0130 + 0x00041> in <filename unknown>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) <0x7f40a0e67630 + 0x00048> in <filename unknown>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f40a0e611e0 + 0x00178> in <filename unknown>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f40a0e611b0 + 0x00020> in <filename unknown>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7f40a0e675c0 + 0x00053> in <filename unknown>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x7f40a0e65b30 + 0x001d6> in <filename unknown>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7f40a0e67440 + 0x00008> in <filename unknown>:0
```

My function is defined as below:

```
        internal static void SendMessageToChannel(ulong steamID, string message) {
            if (steamID == 0 || string.IsNullOrEmpty(message)) {
                return;
            }

            for (int i = 0; i < message.Length; i += MaxSteamMessageLength - 6) {
                string messagePart = (i > 0 ? "..." : "") + message.Substring(i, Math.Min(MaxSteamMessageLength - 6, message.Length - i)) + (MaxSteamMessageLength - 6 < message.Length - i ? "..." : "");
                Logging.LogChannelResponse(steamID, messagePart);
                SteamFriends.SendChatRoomMessage(steamID, EChatEntryType.ChatMsg, messagePart);
            }
        }
```

It's basically a wrapper that splits message into parts if needed.

Both `SteamClient` and `SteamFriends` objects are initialized with `readonly` field in my code, so they're always available, besides, stacktrace would show my function as a culprit if it was a problem with it.

As you can see I also accept steamID only in `ulong` form, and ensure that it's non-zero, I can't say exactly with what paramters that happened, but it was 100% valid call, not malformed one.

I tried to analyze the source code myself and I couldn't find any logical reason why it would happen, I can't also see where exactly it's throwing an exception (apart from `SteamKit2.SteamFriends.SendChatRoomMessage`), I'm more than sure that it's connected with the fact that bot tried to send a message with steam client that was online before, but got disconnected (and still is) at the time of call, could that be a problem? Maybe I'm missing something obvious? Should I add a mandatory check for `SteamClient.IsConnected` before calling SK2 functions?

Thank you in advance.

**Comment by JustArchi** [comment]
Similar issue also in ASF: https://github.com/JustArchi/ArchiSteamFarm/issues/226

```
08 May 2016 10:41:08 AM [!] EXCEPTION: UnhandledExceptionHandler() <Main> Object reference not set to an instance of an object.
08 May 2016 10:41:08 AM [!] StackTrace:
   at SteamKit2.SteamFriends.SendChatRoomMessage(SteamID steamIdChat, EChatEntryType type, String message)
   at ArchiSteamFarm.Bot.SendMessageToChannel(UInt64 steamID, String message)
   at ArchiSteamFarm.Bot.SendMessage(UInt64 steamID, String message)
   at ArchiSteamFarm.Bot.<HandleMessage>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.Bot.<OnChatMsg>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by JustArchi** [comment]
It seems that checking for ```SteamClient.IsConnected``` (and returning if false) before calling ```SteamFriends.SendChatRoomMessage()``` solved this issue.

Leaving it open as you might want to check what's going on deeper, unless it's intended that calling ```SteamFriends.SendChatRoomMessage()``` can throw exception.

**Comment by yaakov-h** [comment]
We now have null checks at the API surface, so something like this _shouldn't_ happen again.

If it does, we have a fun bug somewhere internally that I didn't spot.
