### ISSUE TITLE
alpha8 websocket issues

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#452]
> oh no not that guy again

```
2017-09-12 20:06:55|dotnet-3673|FATAL|ASF|OnUnobservedTaskException() System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The remote party closed the WebSocket connection without completing the close handshake.) ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to transfer data on the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, LazyAsyncResult asyncResult)
   at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to transfer data on the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, LazyAsyncResult asyncResult)
   at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer)<---
```

Original log: https://gist.githubusercontent.com/GUiHKX/822bf93ea5bec76eb3cea72b45a50880/raw/c9458854fd0a060d9e7ea610daa66904c075b40f/log.txt

https://github.com/JustArchi/ArchiSteamFarm/issues/612#issuecomment-329015761

Looks like Steam maintenance once again.

**Comment by ObsidianMinor** [comment]
Do you open an issue for Steam not closing connections properly every alpha release?

**Comment by JustArchi** [comment]
No, I open bugs caused by SteamKit2 library that **[I specifically was asked to do](https://github.com/SteamRE/SteamKit/issues/436#issuecomment-327583037)**. Steam not closing connections properly has nothing to do with SK2 not handling that case in appropriate way.

**Comment by VoiDeD** [comment]
Bug reports are always welcome.

@ObsidianMinor If email/notification churn is a concern, you can un-watch the repository.

**Comment by ObsidianMinor** [comment]
Email/notification churn is fine, it'd just seem like web socket issues would be something to close and reopen in one issue rather than close and forget multiple issues (#422, #436).

**Comment by yaakov-h** [comment]
How the hell do we get an unobserved task exception there?

We already catch the inner `WebSocketException` [here](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Networking/Steam3/WebSocketContext.cs#L101), and failing that we have a catch-all [here](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Networking/Steam3/WebSocketConnection.cs#L46).

This might actually be a bug in .NET Core itself. [This function](https://source.dot.net/#System.Net.WebSockets/Common/System/Net/WebSockets/ManagedWebSocket.cs,519) is invoked by a timer and the task is not observed. All other code paths appear to be properly awaited.

@JustArchi can you please escalate to [dotnet/corefx](https://github.com/dotnet/corefx) with runtime details, os, version, etc.?

**Comment by JustArchi** [comment]
As suggested 🙂

**Comment by yaakov-h** [comment]
Thanks.

.NET Core, like .NET Framework, appears to use WinHttp under the hood on Windows. The unobserved task is from the managed implementation which would be used on other (macOS/Linux/Android/BSD/etc.) platforms.

As such, I don't think you'll have any luck reproducing under Windows.

**Comment by yaakov-h** [comment]
.NET Core PR has been merged.

Closing. You might want to programmatically ignite this exception until the next release of System.Net.WebSockets.

**Comment by JustArchi** [comment]
Exception itself is not a problem, but I'm not sure why the timer is sending those keepalive packets (and failing) long after websocket was closed.

Take a look at last lines of original log I sent above - the exception is popping up for straight 30 minutes since the issue happening, and I guess SK2 should kill the connection long time before that, am I wrong? The unobserved exception was indeed corefx issue, but it looks like websocket is still sending keepalives despite of being closed.

**Comment by yaakov-h** [comment]
We do dispose of the `ClientWebSocket`, which should also kill the timer.

I'll have to dig in deeper and see if we're doing anything funky there.
