### ISSUE TITLE
NRE in 2.0.0 networking code

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#506]
```
2017-12-28 16:44:42|dotnet-9599|FATAL|ASF|OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
at SteamKit2.Internal.CMClient.Disconnected(Object sender, DisconnectedEventArgs e)
at SteamKit2.TcpConnection.Release(Boolean userRequestedDisconnect)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
```

This was reproduced on SK 2.0.0 (latest/final). I'm trying to get more details about this one in the meantime, since stacktrace is everything I have for now.

Thank you in advance and happy new year 🎉

**Comment by azuisleet** [comment]
I believe this is a result of two competing Disconnected calls: for example an explicit Connect or Disconnect and a concurrent connection termination. I've locked the section around connection in Disconnected in e681328.

This assumes that EventHandlers can't block eg by having an ExecutionContext associated that would try to dispatch Disconnected on another thread while blocking a Disconnect call. I need to figure out if this is indeed possible.

**Comment by azuisleet** [comment]
Revised in 14d883b as a deadlock would have been possible when Disconnect holds connectionLock, waits for the setup task, and the setup task tries to call Disconnected.

**Comment by JustArchi** [comment]
> I believe this is a result of two competing Disconnected calls: for example an explicit Connect or Disconnect and a concurrent connection termination.

This is very likely the case, I got some extra details in the meantime.

```
2017-12-29 12:54:45|dotnet-1206|INFO|nicobesser|OnLoggedOff() Logged off of Steam: LoggedInElsewhere
2017-12-29 12:54:45|dotnet-1206|INFO|nicobesser|OnDisconnected() Disconnected from Steam!
2017-12-29 12:54:45|dotnet-1206|INFO|nicobesser|OnDisconnected() Reconnecting...
2017-12-29 12:54:45|dotnet-1206|INFO|nicobesser|Connect() Connecting...
2017-12-29 12:54:45|dotnet-1206|FATAL|ASF|OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamKit2.Internal.CMClient.Disconnected(Object sender, DisconnectedEventArgs e)
   at SteamKit2.TcpConnection.Release(Boolean userRequestedDisconnect)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

My program simply tries to reconnect the moment it received `DisconnectedCallback`. If it's possible that at that moment some connection leftovers are still pending to cleanup, it's very likely the culprit.

**Comment by yaakov-h** [comment]
Anything still to be done here, or is this closable?

**Comment by JustArchi** [comment]
Any chance we can get SK2 2.0.1 or 2.1.0-alpha shipped with this fix? I'd love to further test if anything new pops up, thanks! ❤️

**Comment by azuisleet** [comment]
I believe this is ready.
