### ISSUE TITLE
Crash of SK2 in UDP mode

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#588]
Full stacktrace looks like this:

```
OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamKit2.UdpConnection.SendPacket(UdpPacket packet)
   at SteamKit2.UdpConnection.SendPendingMessages()
   at SteamKit2.UdpConnection.NetLoop(Object param)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

The issue was reproduced by one of my ASF users, full (ASF) log is available **[here](https://pastebin.com/raw/sa8VFbgE)**.

From my observations I do not see any specific event that could lead to the issue, no prior disconnections, no indicator of networking issues. Could it be somehow related with 23 `SteamClient`s running at the same time? Maybe. They were mostly idle so if I had to make a blind call then it could be a heartbeat packet or other ACK, but I'm bad at making blind guesses.

As usual with networking issues reproducing this one might be difficult, all I can see for now is the fact that this issue was reproduced on arm Linux machine.

Thank you in advance for looking into this. I'll try to get `DebugLog` in the meantime, but since I'm unable to reproduce it myself, it might take a while. This was reproduced with latest steamclient-beta https://github.com/SteamRE/SteamKit/commit/4a2bdd21a29a56aac1fbc413ca744e396500d447 SK2 code.

**Comment by azuisleet** [comment]
This could be caused by mutation of `outPackets` by `Send` while `SendPendingMessages` or `ReceivePacket` is mutating it. Though why it might result in an NRE I'm not sure.

**Comment by JustArchi** [comment]
I've got promised `DebugLog` considering this issue and like I expected, this was just idle SteamClient running into it, nothing unusual. Relevant part available **[here](https://pastebin.com/raw/iF1iuZvc)**.

User was running just 2 SteamClients, the exception popped up here:

```
2018-08-28 04:29:20|ArchiSteamFarm-21802|DEBUG|ASF|WriteLine() CMClient | Sent -> EMsg: ClientHeartBeat (Proto: True)
2018-08-28 04:29:20|ArchiSteamFarm-21802|DEBUG|ASF|WriteLine() UdpConnection | Sent -> Data Seq 1514 Ack 190; 48 bytes; Message: 48 bytes 1 packets
2018-08-28 04:29:20|ArchiSteamFarm-21802|DEBUG|ASF|WriteLine() UdpConnection | <- Recv'd Datagram Seq 0 Ack 1514; 0 bytes; Message: 0 bytes 0 packets
2018-08-28 04:29:22|ArchiSteamFarm-21802|DEBUG|ASF|WriteLine() CMClient | Sent -> EMsg: ClientHeartBeat (Proto: True)
2018-08-28 04:29:22|ArchiSteamFarm-21802|FATAL|ASF|OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamKit2.UdpConnection.SendPacket(UdpPacket packet)
   at SteamKit2.UdpConnection.SendPendingMessages()
   at SteamKit2.UdpConnection.NetLoop(Object param)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

Thanks for taking a look.

**Comment by azuisleet** [comment]
I started adding locking in 7e1f4cd

**Comment by JustArchi** [comment]
I've tested SK2 with above commit a bit and it seems that it seems that the issue is solved, thank you a lot!

Leaving the issue open in case you'd want to make any additional follow-up commits. If nothing like that is planned, feel free to close it anytime.

Thanks!
