### ISSUE TITLE
Protobuf dumper crashes on libtensorflow.so

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#593]
This binary exists in Dota 2.

```
Loading binary 'libtensorflow.so'...
tensorflow/core/grappler/costs/op_performance_data.proto... needs rescan: Attempted to read past the end of the stream.
tensorflow/core/grappler/costs/op_performance_data.proto... needs rescan: Attempted to read past the end of the stream.
tensorflow/core/grappler/costs/op_performance_data.proto... OK!

  ! Outputting proto to 'libtensorflow\tensorflow/core/grappler/costs/op_performance_data.proto'

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key 'tensorflow.DataType' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ProtobufDumper.ImageFile.FinalPassWriteFiles() in ProtobufDumper\ImageFile.cs:line 363
   at ProtobufDumper.ImageFile.Process() in ProtobufDumper\ImageFile.cs:line 111
   at ProtobufDumper.Program.Main(String[] args) in ProtobufDumper\Program.cs:line 24
```

**Comment by azuisleet** [comment]
Resolved in #671 by including both libtensorflow.so and libtensorflow_framework.so when running ProtobufDumper.
