### ISSUE TITLE
Protobuf dumper crashes in `game/dota/bin/linuxsteamrt64/libclient.so`

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#814]
```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key 'EEvent' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ProtobufDumper.ImageFile.FinalPassWriteFiles() in /home/steamdb/ProtobufDumper/ProtobufDumper/ImageFile.cs:line 366
   at ProtobufDumper.ImageFile.Process() in /home/steamdb/ProtobufDumper/ProtobufDumper/ImageFile.cs:line 114
   at ProtobufDumper.Program.Main(String[] args) in /home/steamdb/ProtobufDumper/ProtobufDumper/Program.cs:line 24
../common.sh: line 6: 21676 Aborted                 (core dumped) dotnet 
```

**Comment by xPaw** [comment]
Turns out I didn't have latest code running, rebuilt on master and it doesn't throw anymore.

a7cfa25a564c6681c204d6a0751539d033fbafbe would have fixed it
