### ISSUE TITLE
Exception while setting up connection using Client.Connect() directly

### ISSUE THREAD

**Issue by iebb** [SteamRE/SteamKit#860]
unable to connect using `client.Connect()`

Debug Log:
```
TcpConnection: Connecting to 153.254.86.181:27017...
TcpConnection: Connected to 153.254.86.181:27017
TcpConnection: Exception while setting up connection to 153.254.86.181:27017: System.Net.Sockets.SocketException (0x80004005): The system detected an invalid pointer address in attempting to use a pointer argument in a call
   at System.Net.Sockets.Socket.get_RemoteEndPoint()
   at SteamKit2.TcpConnection.ConnectCompleted(Boolean success) in C:\projects\steamkit\SteamKit2\SteamKit2\Networking\Steam3\TcpConnection.cs:line 130
```

However, the following code does work (exact same ip from debug log)
```
client.Connect(
  ServerRecord.CreateSocketServer(new IPEndPoint(IPAddress.Parse("153.254.86.181"), 27017))
);
```

ISP: China Unicom (Hong Kong)
OS: Windows 10 Pro, 1909 Build 18363.836
.NET Framework 4.7.2

**Comment by yaakov-h** [comment]
I can't reproduce this at all, Windows 10 v2004, on either .NET Framework 4.7.2 or .NET Core.

```
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook: Created nethook directory: D:\Development\SteamRE\SteamKit\Samples\3.DebugLog\bin\Debug\netcoreapp2.0\nethook\1591541452
Connecting to Steam...
MyListener - ServerList: Resolving server list
MyListener - ServerList: Server list provider had no entries, will query SteamDirectory
MyListener - ServerList: Resolved 200 servers
MyListener - ServerList: Next server candidiate: 153.254.86.181:27017 (Tcp)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/TcpConnection: Connecting to 153.254.86.181:27017...
MyListener - 3fd31933f5434bf2b4c0690cb0172148/TcpConnection: Connected to 153.254.86.181:27017
MyListener - 3fd31933f5434bf2b4c0690cb0172148/EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
MyListener - 3fd31933f5434bf2b4c0690cb0172148/EnvelopeEncryptedConnection: Encryption result: OK
Connected to Steam! Logging in '[REDACTED]'...
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook: Sent -> EMsg: ClientLogon (5514)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientServersAvailable (5501)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientServersAvailable (5501)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientLogOnResponse (751)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook: Sent -> EMsg: ClientHeartBeat (703)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientAccountInfo (768)
Successfully logged on!
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientAccountInfo (768)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientEmailAddrInfo (5456)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientFriendsList (767)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook: Sent -> EMsg: ClientRequestFriendData (815)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPlayerNicknameList (5587)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientLicenseList (780)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientUpdateGuestPassesList (798)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientWalletInfoUpdate (5528)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientGameConnectTokens (779)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientSessionToken (850)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientIsLimitedAccount (5430)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientCMList (783)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientRequestedClientStats (5480)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientVACBanStatus (782)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientUpdateMachineAuth (5537)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientFriendsGroupsList (5553)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientNewLoginKey (5463)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientPersonaState (766)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook:  <- Recv'd EMsg: ClientMarketingMessageUpdate2 (5510)
MyListener - 3fd31933f5434bf2b4c0690cb0172148/NetHook: Sent -> EMsg: ClientHeartBeat (703)
```

Your log output looks a bit outdated... try using the latest package, [2.3.0-beta.2](https://www.nuget.org/packages/SteamKit2/2.3.0-beta.2).

**Comment by xPaw** [comment]
Perhaps this could be related to the fact that China realm only has websocket servers?

https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?cellid=47&steamrealm=steamchina
